DROP TABLE IF EXISTS actions;
CREATE DATABASE tamagotchi_db;
USE tamagotchi_db;

CREATE TABLE actions
(
	id int NOT NULL AUTO_INCREMENT,
	description varchar(255) NOT NULL,
	completed BOOLEAN DEFAULT false,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
